# Class Meeting 8
### 2022-02-28

## Interpolation

The approximation of the value of a function for points in between the value that we do know.

Fitting a function sounds very familiar; however, they are trying to achieve different things.

* _Interpolation_ seeks to fill in the information in some small region of a dataset.
* _Fitting a function_ attempts to find a model that fits our data to give us some better understanding of the nature of the data.

### Linear Interpolation

Take the two points closest to where you want to interpolate, fit a line to them and then from the equation for that line you have the value of your previously unknown point

Note that you point doesn't need to lie between the two points, though the farther away it is the worst your interpolation is likely to be.

It can be shown that the error in your interpolation $\Delta f(x)$ goes like
<br>
$\Delta f(x) = \frac{1}{2} f'' (x) (x-x_i)(x-x_{i+1})$
<br>

The interpolated value will have some error from the correct value.

The closer x is to a and b, the better the interpolation will be.

### Quadratic Interpolation

Next we can fit a quadratic to three points an duse that for the interpolation.

One thing that happens with a quadratic is that our interpolated value can be outside the range of the points we use to generate it. f(x) can be larger or smaller than f(x_k-1), f(x_k) and f(x_k+1).

This overshooting or undershooting can cause problems if it gives nonphysical answers, That is if the values should only lie in some range.

This is one problem with higher order interpolation.

### Lagrange Interpolation

We can use Lagrange interpolation like we saw when discussing Gaussian quadrature. That is using the interpolating polynomial.

#### Runge Phenomena

You'll notice that at some point as the number of points increases, the error actually increases.

This is an example of the runge phenomena:
* Oscillation becomes large at the end of the interval with polynomial interpolation.

One can do better with variable spacing. The problem is that you have very little information at the end points to constrain the fit. Thus, high order polynomials will tend to trade wild oscillations at the end points for better fits to the middle points.

### Splines

Another way to do interpolation is to match the derivative of the function at the end points. This is called a spline.

The most common one used is a cubic spline that matches the first and second derivative at each data point.

This results in a smooth appearance and avoids the severe oscillations of higher order polynomials.

The goal here is not to fit a large number of points,  bu tto combine a number of different fits so that they pass through the points and their derivatives match where they connect.

Splines do not provide a functional fit to the entire dataset.

Not a good representation of reality since splines use multiple functions between several points.


In [1]:
import numpy as np

matrix = np.matrix([[4, -1, -1, -1, 5],
                    [-1, 3, 0, -1, 0],
                    [-1, 0, 3, -1, 5],
                    [-1, -1, -1, 4, 0]])



def upper_triangle(a):
    print(a)
    
    a[0] = a[0] / a[0,0]
    a[1] = a[1] - a[0] * a[1,0]
    a[2] = a[2] - a[0] * a[2,0]
    a[3] = a[3] - a[0] * a[3,0]

    a[1] = a[1] / a[1, 1]
    a[2] = a[2] - a[1] * a[2,1]
    a[3] = a[3] - a[1] * a[3,1]

    a[2] = a[2] / a[2, 2]
    a[3] = a[3] - a[2] * a[3,2]

    a[3] = a[3] / a[3, 3]

    print(a)

upper_triangle(matrix)

[[ 4 -1 -1 -1  5]
 [-1  3  0 -1  0]
 [-1  0  3 -1  5]
 [-1 -1 -1  4  0]]
[[1 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 2]
 [0 0 0 1 0]]
